export const GET_MEDIA_REQUEST = "GET_MEDIA_REQUEST"
export const GET_MEDIA_SUCCESS = "GET_MEDIA_SUCCESS"
export const GET_MEDIA_FAILURE = "GET_MEDIA_FAILURE"

export const POST_MEDIA_REQUEST = "POST_MEDIA_REQUEST"
export const POST_MEDIA_SUCCESS = "POST_MEDIA_SUCCESS"
export const POST_MEDIA_FAILURE = "POST_MEDIA_FAILURE"

export const EDIT_MEDIA_REQUEST = "EDIT_MEDIA_REQUEST"
export const EDIT_MEDIA_SUCCESS = "EDIT_MEDIA_SUCCESS"
export const EDIT_MEDIA_FAILURE = "EDIT_MEDIA_FAILURE"

export const DELETE_MEDIA_REQUEST = "DELETE_MEDIA_REQUEST"
export const DELETE_MEDIA_SUCCESS = "DELETE_MEDIA_SUCCESS"
export const DELETE_MEDIA_FAILURE = "DELETE_MEDIA_FAILURE"