export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST"
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS"
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE"

export const POST_PROJECT_REQUEST = "POST_PROJECT_REQUEST"
export const POST_PROJECT_SUCCESS = "POST_PROJECT_SUCCESS"
export const POST_PROJECT_FAILURE = "POST_PROJECT_FAILURE"

